
[[Snippets]]
  Description = "Configure FastFetch"
  Output = ""
  Tag = []
  command = "micro ~/.config/fastfetch/config.jsonc"

[[Snippets]]
  Description = "Set brightness for monitor"
  Output = ""
  Tag = []
  command = "xrandr --output DisplayPort-1 --brightness <0-1>"

[[Snippets]]
  Description = "ASUS Control Options"
  Output = ""
  Tag = []
  command = "asusctl --help"

[[Snippets]]
  Description = "Manage ASUS GPU"
  Output = ""
  Tag = []
  command = "supergfxctl -h"

[[Snippets]]
  Description = "Find Packages"
  Output = ""
  Tag = []
  command = "apt-cache search . | fzf --preview 'apt-cache show {1}'"

[[Snippets]]
  Description = "Check System Information"
  Output = ""
  Tag = []
  command = "inxi -b"

[[Snippets]]
  Description = "Firefly III Backup"
  Output = ""
  Tag = []
  command = "bash firefly-iii-backuper.sh backup ~/firefly-iii_backups/$(date '+%F').tar"

[[Snippets]]
  Description = "Firefly III Restore"
  Output = ""
  Tag = []
  command = "bash firefly-iii-backuper.sh restore ~/firefly-iii_backups/<YYYY-MM-DD>.tar"
